# Site settings
title: Omit
email: derek.wheelden@gmail.com
description: "A blog written by Derek Wheelden about front-end web development, CSS, JavaScript, and lots of other things."
baseurl: ""
url: "http://omit.io"

# Build settings
markdown: kramdown
permalink: pretty

# More settings
source: _jekyll
destination: _dist
timezone: America/New_York
